server:
  port: 8088

spring:
  application:
    name: analytics-api

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:redis_pass}
    timeout: 2000ms

  cache:
    type: redis
    redis:
      time-to-live: 300000
      cache-null-values: false

  datasource:
    driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
    url: jdbc:clickhouse://${CLICKHOUSE_HOST:localhost}:8123/${CLICKHOUSE_DB:analytics}
    username: ${CLICKHOUSE_USER:admin}
    password: ${CLICKHOUSE_PASSWORD:clickhouse_pass}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    ru.faustus: INFO
    org.springframework.cache: DEBUG