global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'analytics-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['analytics-api:8088']

  - job_name: 'data-generator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['data-generator:8080']